CC = gcc  
LD = gcc  
CFLAGS = -Wall -c -Dgliethttp -I../include -L lib_path  
LDFLAGS = -lpthread     
SRCS = $(wildcard *.c source/*.c)  
OBJS = $(patsubst %c, %o, $(SRCS))  
TARGET = gliethttp  
.PHONY: all clean     
all: $(TARGET)     
$(TARGET): $(OBJS)  
    $(LD) $(LDFLAGS) -o $@ $^     
%o: %c  
    $(CC) $(CFLAGS) -o $@ $<     
clean:  
    rm -f *.o $(TARGET)  

    